import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-resume-wrapper',
  templateUrl: './resume-wrapper.component.html',
  styleUrls: ['./resume-wrapper.component.css']
})
export class ResumeWrapperComponent implements OnInit {
  sampleEducation = "<p><span style='color: rgb(0, 0, 0); font-family: \"Open Sans\", Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;'>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati<\/span><\/p>\r\n<ol>\r\n    <li><span style='color: rgb(0, 0, 0); font-family: \"Open Sans\", Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;'>&nbsp;cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.<\/span><\/li>\r\n    <li><span style='color: rgb(0, 0, 0); font-family: \"Open Sans\", Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;'>&nbsp;Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.<\/span><\/li>\r\n<\/ol>";
  sampleExp = [
    "<ul style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Created an online development environment with source control. shell access and deployment centre using Theia and GKE.<\/span><\/li>\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Created a code compilation system which is a docker based sandbox to run the code and return the output to the app. This service is serverless using Google Cloud-Run.<\/span><\/li>\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Interviewed prospective employees and mentored junior software developers on the team<\/span><\/li>\r\n<\/ul>\r\n<p style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\"><br><\/p>",
    "<ul style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Created an ATS in Juntrax Platform which is highly appreciated by clients.<\/span><\/li>\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Created a report generation tool which is highly customizable using MongoDb aggregate and AWS lambda.<\/span><\/li>\r\n    <li style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt; list-style-type:disc;\"><span data-preserver-spaces=\"true\" style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\">Created and optimized graphic prototype websites and applications interfaces using HTML and CSS.<\/span><\/li>\r\n<\/ul>\r\n<p style=\"color: rgb(14, 16, 26); background: transparent; margin-top:0pt; margin-bottom:0pt;\"><br><\/p>"
  ]
  constructor() { }

  ngOnInit() {
  }

}
